version: '2'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongodb

  mongodb:
    image: "mongo:latest"

  # adds initial data to our mongoDB
  mongo-seed:
    image: mongo:latest
    environment:
      - NODE_ENV=production
    links:
      - mongodb
    volumes:
      - ./initial_data:/initial_data
    command:
      './initial_data/seed.sh'